#ifndef VISUALIZACION_HPP
#define VISUALIZACION_HPP

enum visualizacion {ALAMBRE,SOLIDO,AJEDREZ,PUNTOS, SOLIDO_CARAS};
enum normales {NADA,CARAS,VERTICES,AMBAS};
enum figuras {NINGUNA,ESFERA,CUBO,CONO,CILINDRO,TORO,DODECAEDRO,OCTAEDRO,TETRAEDRO,ICOSAEDRO,TETERA};

#endif
